# Corridors config

# Lines config
lines:
  probabilities:
      '1': 0.2
      '2': 0.07
      '3': 0.02
      '4': 0.04
      '5': 0.26
      '6': 0.04
      '7': 0.07
      '8': 0.02
      '9': 0.04
      '10': 0.03
      '11': 0.03
      '12': 0.05
      '13': 0.02
      '14': 0.06
      '15': 0.03
      '16': 0.02

time_slots:
  probabilities:
      1: 0.01
      2: 0.01
      3: 0.01
      4: 0.01
      5: 0.02
      6: 0.04
      7: 0.05
      8: 0.06
      9: 0.06
      10: 0.05
      11: 0.04
      12: 0.05
      13: 0.06
      14: 0.06
      15: 0.06
      16: 0.06
      17: 0.06
      18: 0.06
      19: 0.06
      20: 0.06
      21: 0.05
      22: 0.03
      23: 0.02

tsps:
  probabilities:
    '1': 0.25
    '2': 0.25
    '3': 0.3
    '4': 0.2
    '5': 0.2

# Prices config
prices:
  base: 10  # Base price
  max: 150  # Max price
  distance_factor: 0.05  # Increase price with a factor of f * min_price per station in corridor
  tsp_factor:  # Defines how the TSP affects the price (multiplies each price by the factor)
      '1': 1.5  # Renfe AVE
      '2': 1.1  # Renfe AVLO
      '3': 1  # Iryo
      '4': 0.5  # Ouigo
      '5': 0.5
  seat_type_factor:  # Defines how the seat type affects the price (multiplies each price by the factor)
      '1': 1  # Tourist Class
      '2': 1.2 # Tourist Plus Class
      '3': 1.6  # Business Class

# Service config
services:
  dates: # Set range for random dates
    min: 2025-06-25
    max: 2025-06-26