stations:
- id: 'Guadalajara'
  name: Guadalajara
  city: Guadalajara
  short_name: GUA
  coordinates:
    latitude: 40.6441032
    longitude: -3.1822298
- id: 'Barcelona'
  name: Barcelona-Sants
  city: Barcelona
  short_name: BAR
  coordinates:
    latitude: 41.37922
    longitude: 2.140624
- id: 'Girona'
  name: Girona
  city: Girona
  short_name: GIR
  coordinates:
    latitude: 41.979303
    longitude: 2.817006
- id: 'Tarragona'
  name: Tarragona
  city: Tarragona
  short_name: TAR
  coordinates:
    latitude: 41.111624
    longitude: 1.253214
- id: 'Lleida'
  name: Lleida
  city: Lleida
  short_name: LLE
  coordinates:
    latitude: 41.620696
    longitude: 0.632669
- id: 'Zaragoza'
  name: Zaragoza-Delicias
  city: Zaragoza
  short_name: ZAR
  coordinates:
    latitude: 41.658649
    longitude: -0.911615
- id: 'Madrid'
  name: Madrid-Puerta de Atocha
  city: Madrid
  short_name: MAD
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: 'Figueres'
  name: Figueres Vilafant
  city: Figueres
  short_name: FIG
  coordinates:
    latitude: 42.264771
    longitude: 2.943547
- id: 'Calatayud'
  name: Calatayud
  city: Calatayud
  short_name: CAL
  coordinates:
    latitude: 41.346692
    longitude: -1.63868
seat:
- id: '1'
  name: 'Turista'
  hard_type: 1
  soft_type: 1
- id: '2'
  name: 'TuristaPlus'
  hard_type: 1
  soft_type: 2
- id: '3'
  name: 'Premium'
  hard_type: 2
  soft_type: 3
corridor:
- id: '1'
  name: 'Corredor Noreste'
  stations:
  - org: 'Madrid'
    des:
    - org: 'Guadalajara'
      des:
      - org: 'Calatayud'
        des:
        - org: 'Zaragoza'
          des:
          - org: 'Lleida'
            des:
            - org: 'Tarragona'
              des:
              - org: 'Barcelona'
                des:
                - org: 'Girona'
                  des:
                  - org: 'Figueres'
                    des: []
rollingStock:
- id: '11'
  name: 'RU1 RS1'
  seats:
  - hard_type: 1
    quantity: 200
  - hard_type: 2
    quantity: 50
- id: '12'
  name: 'RU1 RS2'
  seats:
  - hard_type: 1
    quantity: 250
  - hard_type: 2
    quantity: 50
- id: '13'
  name: 'RU1 RS3'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '21'
  name: 'RU2 RS1'
  seats:
  - hard_type: 1
    quantity: 300
- id: '22'
  name: 'RU2 RS2'
  seats:
  - hard_type: 1
    quantity: 350
- id: '31'
  name: 'RU2 RS1'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '32'
  name: 'RU2 RS2'
  seats:
  - hard_type: 2
    quantity: 450
- id: '41'
  name: 'RU3 RS1'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '42'
  name: 'RU3 RS2'
  seats:
  - hard_type: 1
    quantity: 350
  - hard_type: 2
    quantity: 50
- id: '51'
  name: 'RU5 RS1'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '52'
  name: 'RU5 RS2'
  seats:
  - hard_type: 1
    quantity: 350
  - hard_type: 2
    quantity: 50
trainServiceProvider:
- id: '1'
  name: 'RU1'
  rolling_stock:
  - '11'
  - '12'
  - '13'
- id: '2'
  name: 'RU2'
  rolling_stock:
  - '21'
  - '22'
- id: '3'
  name: 'RU3'
  rolling_stock:
  - '41'
  - '42'
- id: '4'
  name: 'RU4'
  rolling_stock:
  - '31'
  - '32'
- id: '5'
  name: 'RU5'
  rolling_stock:
  - '51'
  - '52'
line:
- id: '1'
  name: 'ZAR - LLE - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Zaragoza'
    arrival_time: 0
    departure_time: 1
  - station: 'Lleida'
    arrival_time: 46
    departure_time: 48
  - station: 'Tarragona'
    arrival_time: 77
    departure_time: 79
  - station: 'Barcelona'
    arrival_time: 117
    departure_time: 117
- id: '2'
  name: 'MAD - GUA - CAL'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Guadalajara'
    arrival_time: 23
    departure_time: 24
  - station: 'Calatayud'
    arrival_time: 66
    departure_time: 66
- id: '3'
  name: 'MAD - GUA - CAL - ZAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Guadalajara'
    arrival_time: 23
    departure_time: 24
  - station: 'Calatayud'
    arrival_time: 66
    departure_time: 67
  - station: 'Zaragoza'
    arrival_time: 92
    departure_time: 92
- id: '4'
  name: 'MAD - CAL - ZAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Calatayud'
    arrival_time: 55
    departure_time: 56
  - station: 'Zaragoza'
    arrival_time: 81
    departure_time: 82
  - station: 'Barcelona'
    arrival_time: 171
    departure_time: 171
- id: '5'
  name: 'MAD - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Barcelona'
    arrival_time: 150
    departure_time: 150
- id: '6'
  name: 'MAD - GUA - ZAR - LLE - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Guadalajara'
    arrival_time: 23
    departure_time: 24
  - station: 'Zaragoza'
    arrival_time: 81
    departure_time: 82
  - station: 'Lleida'
    arrival_time: 127
    departure_time: 129
  - station: 'Tarragona'
    arrival_time: 158
    departure_time: 160
  - station: 'Barcelona'
    arrival_time: 198
    departure_time: 198
- id: '7'
  name: 'MAD - ZAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Zaragoza'
    arrival_time: 75
    departure_time: 76
  - station: 'Barcelona'
    arrival_time: 165
    departure_time: 165
- id: '8'
  name: 'MAD - ZAR - LLE - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Zaragoza'
    arrival_time: 75
    departure_time: 76
  - station: 'Lleida'
    arrival_time: 121
    departure_time: 123
  - station: 'Tarragona'
    arrival_time: 152
    departure_time: 154
  - station: 'Barcelona'
    arrival_time: 192
    departure_time: 192
- id: '9'
  name: 'MAD - CAL - ZAR - LLE - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Calatayud'
    arrival_time: 55
    departure_time: 56
  - station: 'Zaragoza'
    arrival_time: 81
    departure_time: 82
  - station: 'Lleida'
    arrival_time: 127
    departure_time: 129
  - station: 'Tarragona'
    arrival_time: 158
    departure_time: 160
  - station: 'Barcelona'
    arrival_time: 198
    departure_time: 198
- id: '10'
  name: 'MAD - ZAR - LLE - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Zaragoza'
    arrival_time: 75
    departure_time: 76
  - station: 'Lleida'
    arrival_time: 121
    departure_time: 123
  - station: 'Barcelona'
    arrival_time: 192
    departure_time: 192
- id: '11'
  name: 'MAD - ZAR - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Zaragoza'
    arrival_time: 75
    departure_time: 76
  - station: 'Tarragona'
    arrival_time: 132
    departure_time: 134
  - station: 'Barcelona'
    arrival_time: 172
    departure_time: 172
- id: '12'
  name: 'MAD - GUA - CAL - ZAR - LLE - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Guadalajara'
    arrival_time: 23
    departure_time: 24
  - station: 'Calatayud'
    arrival_time: 66
    departure_time: 67
  - station: 'Zaragoza'
    arrival_time: 92
    departure_time: 93
  - station: 'Lleida'
    arrival_time: 138
    departure_time: 140
  - station: 'Tarragona'
    arrival_time: 169
    departure_time: 171
  - station: 'Barcelona'
    arrival_time: 209
    departure_time: 209
- id: '13'
  name: 'MAD - GUA - ZAR - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Madrid'
    arrival_time: 0
    departure_time: 0
  - station: 'Guadalajara'
    arrival_time: 23
    departure_time: 24
  - station: 'Zaragoza'
    arrival_time: 81
    departure_time: 82
  - station: 'Tarragona'
    arrival_time: 138
    departure_time: 140
  - station: 'Barcelona'
    arrival_time: 178
    departure_time: 178
- id: '14'
  name: 'LLE - TAR - BAR'
  corridor: '1'
  stops:
  - station: 'Lleida'
    arrival_time: 0
    departure_time: 2
  - station: 'Tarragona'
    arrival_time: 31
    departure_time: 33
  - station: 'Barcelona'
    arrival_time: 71
    departure_time: 71
- id: '15'
  name: 'LLE - BAR'
  corridor: '1'
  stops:
  - station: 'Lleida'
    arrival_time: 0
    departure_time: 2
  - station: 'Barcelona'
    arrival_time: 71
    departure_time: 71
- id: '16'
  name: 'CAL - ZAR'
  corridor: '1'
  stops:
  - station: 'Calatayud'
    arrival_time: 0
    departure_time: 1
  - station: 'Zaragoza'
    arrival_time: 26
    departure_time: 26