stations:
- id: '70200'
  name: Guadalajara
  city: Guadalajara
  short_name: GUA
  coordinates:
    latitude: 40.6441032
    longitude: -3.1822298
- id: '71801'
  name: Barcelona-Sants
  city: Barcelona
  short_name: BAR
  coordinates:
    latitude: 41.37922
    longitude: 2.140624
- id: '79300'
  name: Girona
  city: Girona
  short_name: GIR
  coordinates:
    latitude: 41.979303
    longitude: 2.817006
- id: '71500'
  name: Tarragona
  city: Tarragona
  short_name: TAR
  coordinates:
    latitude: 41.111624
    longitude: 1.253214
- id: '78400'
  name: Lleida
  city: Lleida
  short_name: LLE
  coordinates:
    latitude: 41.620696
    longitude: 0.632669
- id: '04040'
  name: Zaragoza-Delicias
  city: Zaragoza
  short_name: ZAR
  coordinates:
    latitude: 41.658649
    longitude: -0.911615
- id: '60000'
  name: Madrid-Puerta de Atocha
  city: Madrid
  short_name: MAD
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: '04307'
  name: Figueres Vilafant
  city: Figueres
  short_name: FIG
  coordinates:
    latitude: 42.264771
    longitude: 2.943547
- id: '70600'
  name: Calatayud
  city: Calatayud
  short_name: CAL
  coordinates:
    latitude: 41.346692
    longitude: -1.63868
seat:
- id: '1'
  name: 'Turista'
  hard_type: 1
  soft_type: 1
- id: '2'
  name: 'Turista Plus'
  hard_type: 1
  soft_type: 2
- id: '3'
  name: 'Premium'
  hard_type: 2
  soft_type: 3
corridor:
- id: '1'
  name: 'Corredor Noreste'
  stations:
  - org: '60000'
    des:
    - org: '70200'
      des:
      - org: '70600'
        des:
        - org: '04040'
          des:
          - org: '78400'
            des:
            - org: '71500'
              des:
              - org: '71801'
                des:
                - org: '79300'
                  des:
                  - org: '04307'
                    des: []
rollingStock:
- id: '11'
  name: 'AVE RS1'
  seats:
  - hard_type: 1
    quantity: 200
  - hard_type: 2
    quantity: 50
- id: '12'
  name: 'AVE RS2'
  seats:
  - hard_type: 1
    quantity: 250
  - hard_type: 2
    quantity: 50
- id: '13'
  name: 'AVE RS3'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '21'
  name: 'AVLO RS1'
  seats:
  - hard_type: 1
    quantity: 300
- id: '22'
  name: 'AVLO RS2'
  seats:
  - hard_type: 1
    quantity: 350
- id: '31'
  name: 'OUIGO RS1'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '32'
  name: 'OUIGO RS2'
  seats:
  - hard_type: 2
    quantity: 450
- id: '41'
  name: 'IRYO RS1'
  seats:
  - hard_type: 1
    quantity: 300
  - hard_type: 2
    quantity: 50
- id: '42'
  name: 'IRYO RS2'
  seats:
  - hard_type: 1
    quantity: 350
  - hard_type: 2
    quantity: 50
trainServiceProvider:
- id: '1'
  name: 'Renfe AVE'
  rolling_stock:
  - '11'
  - '12'
  - '13'
- id: '2'
  name: 'Renfe AVLO'
  rolling_stock:
  - '21'
  - '22'
- id: '3'
  name: 'OUIGO'
  rolling_stock:
  - '31'
  - '32'
- id: '4'
  name: 'IRYO'
  rolling_stock:
  - '41'
  - '42'
line:
- id: '03612'
  name: 'MAD - BCN'
  corridor: '1'
  stops:
  - station: '60000'
    arrival_time: 0
    departure_time: 0
  - station: '71801'
    arrival_time: 150
    departure_time: 150
- id: '04161'
  name: 'Stops MAD - BCN'
  corridor: '1'
  stops:
  - station: '60000'
    arrival_time: 0
    departure_time: 0
  - station: '70600'
    arrival_time: 55
    departure_time: 56
  - station: '04040'
    arrival_time: 81
    departure_time: 82
  - station: '78400'
    arrival_time: 125
    departure_time: 127
  - station: '71500'
    arrival_time: 154
    departure_time: 156
  - station: '71801'
    arrival_time: 192
    departure_time: 192
- id: '02731'
  name: 'Main Stops MAD - BCN'
  corridor: '1'
  stops:
  - station: '60000'
    arrival_time: 0
    departure_time: 0
  - station: '04040'
    arrival_time: 75
    departure_time: 77
  - station: '71500'
    arrival_time: 150
    departure_time: 152
  - station: '71801'
    arrival_time: 185
    departure_time: 185
timeSlot:
- id: '1'
  start: '7:30:00'
  end: '7:40:00'
- id: '2'
  start: '18:00:00'
  end: '18:10:00'
- id: '3'
  start: '8:30:00'
  end: '8:40:00'